# INTRODUCTION TO DEEP LEARNING WITH PYTORCH

>In this notebook, I am going to practice all what i have learnt for deep learning. 

#### `TENSOR`

 * Similar to array or matrix
 * Building block of neural network

In [1]:
# import libraries
import torch

my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)

print("shape of the tensor:", tensor.shape)
print("dtype of the tensor:", tensor.dtype)

shape of the tensor: torch.Size([2, 3])
dtype of the tensor: torch.int64


#### `Single Linear Layer`

In [2]:
import torch.nn as nn

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_layer = nn.Linear(in_features = 3,
                         out_features= 2)
output = linear_layer(input_tensor)
print(output)

tensor([[ 0.1910, -0.6155]], grad_fn=<AddmmBackward0>)


### `Addition of tensors`

tensors can be added if the have same dimesion

In [3]:
temperature = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperature
temp_tensor = torch.tensor(temperature)
print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


In [4]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])
adjust_temp = temp_tensor + adjustment

print(adjust_temp)

tensor([[74, 77, 80],
        [72, 75, 78]])


In [5]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(
    nn.Linear(8, 4),
    nn.Linear(4, 1)
)

output = model(input_tensor)
print(output)

tensor([[1.8131]], grad_fn=<AddmmBackward0>)


In [6]:
input_tensor = torch.Tensor([[2, 7, 9, 5, 3]])

#Create neural network with three hidden layers
model = nn.Sequential(nn.Linear(5, 10),
                      nn.Linear(10, 15),
                      nn.Linear(15, 2))

output = model(input_tensor)
print(output)

tensor([[-1.2374,  1.3487]], grad_fn=<AddmmBackward0>)


In [7]:
model = nn.Sequential(nn.Linear(8, 4),
                      nn.Linear(4, 1))

# Calculate the number of parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 41


### `Multiplication of matrix`

* A * B is called elements wise multiplications
* A @ B is called matrix multiplications
  

In [8]:
print(temp_tensor * adjustment)

tensor([[144, 150, 156],
        [140, 146, 152]])


### `Sigmoid Activation`
The sigmoid function is essential for binary classification.

In [1]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([6.0])

# Apply sigmoid activation function
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([0.9975])


This value indicates a high likelihood of the input belonging to the positive class

### `Softmax`
The softmax activation function is use for multi-class classification problems.

In [3]:
input_tensor = torch.tensor([2.0, 3.0, 5.0])

# Applying sofmax activation function
softmax = nn.Softmax(dim=-1)
output = softmax(input_tensor)
print(output)

tensor([0.0420, 0.1142, 0.8438])


### `Neural Networks and Activation Functions`

In [5]:
model= nn.Sequential(nn.Linear(3, 1),
                     nn.Sigmoid())

input_tensor = torch.tensor([[1.0, 0.0, 1.0]])

output = model(input_tensor)
print(output)

tensor([[0.4445]], grad_fn=<SigmoidBackward0>)


### `Running a Forward Pass`

In [10]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.layer1 = nn.Linear(6, 4)
        self.layer2 = nn.Linear(4, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x
    
# Example input data: 5 animals with 6 features each
input_data = torch.randn(5, 6)
model = SimpleNet()
output = model(input_data)
print(output)

tensor([[0.4633],
        [0.5607],
        [0.6028],
        [0.7641],
        [0.4234]], grad_fn=<SigmoidBackward0>)


The output is a tensor of probabilities for each animal being mammal. Probabilities above 0.5 are classified as `mammals`