# INTRODUCTION TO DEEP LEARNING WITH PYTORCH

>In this notebook, I am going to practice all what i have learnt for deep learning. 

#### `TENSOR`

 * Similar to array or matrix
 * Building block of neural network

In [1]:
# import libraries
import torch

my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)

print("shape of the tensor:", tensor.shape)
print("dtype of the tensor:", tensor.dtype)

shape of the tensor: torch.Size([2, 3])
dtype of the tensor: torch.int64


#### `Single Linear Layer`

In [2]:
import torch.nn as nn

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_layer = nn.Linear(in_features = 3,
                         out_features= 2)
output = linear_layer(input_tensor)
print(output)

tensor([[-0.0111, -0.8740]], grad_fn=<AddmmBackward0>)


### `Addition of tensors`

tensors can be added if the have same dimesion

In [3]:
temperature = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperature
temp_tensor = torch.tensor(temperature)
print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


In [4]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])
adjust_temp = temp_tensor + adjustment

print(adjust_temp)

tensor([[74, 77, 80],
        [72, 75, 78]])


In [5]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(
    nn.Linear(8, 4),
    nn.Linear(4, 1)
)

output = model(input_tensor)
print(output)

tensor([[1.0628]], grad_fn=<AddmmBackward0>)


In [6]:
input_tensor = torch.Tensor([[2, 7, 9, 5, 3]])

#Create neural network with three hidden layers
model = nn.Sequential(nn.Linear(5, 10),
                      nn.Linear(10, 15),
                      nn.Linear(15, 2))

output = model(input_tensor)
print(output)

tensor([[0.0745, 0.9390]], grad_fn=<AddmmBackward0>)


In [7]:
model = nn.Sequential(nn.Linear(8, 4),
                      nn.Linear(4, 1))

# Calculate the number of parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 41
