# INTRODUCTION TO DEEP LEARNING WITH PYTORCH

>In this notebook, I am going to practice all what i have learnt for deep learning. 

#### `TENSOR`

 * Similar to array or matrix
 * Building block of neural network

In [1]:
# import libraries
import torch

my_list = [[1, 2, 3], [4, 5, 6]]
tensor = torch.tensor(my_list)

print("shape of the tensor:", tensor.shape)
print("dtype of the tensor:", tensor.dtype)

shape of the tensor: torch.Size([2, 3])
dtype of the tensor: torch.int64


#### `Single Linear Layer`

In [2]:
import torch.nn as nn

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_layer = nn.Linear(in_features = 3,
                         out_features= 2)
output = linear_layer(input_tensor)
print(output)

tensor([[-0.4361, -0.5689]], grad_fn=<AddmmBackward0>)


### `Addition of tensors`

tensors can be added if the have same dimesion

In [3]:
temperature = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperature
temp_tensor = torch.tensor(temperature)
print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


In [4]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])
adjust_temp = temp_tensor + adjustment

print(adjust_temp)

tensor([[74, 77, 80],
        [72, 75, 78]])


In [5]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(
    nn.Linear(8, 4),
    nn.Linear(4, 1)
)

output = model(input_tensor)
print(output)

tensor([[1.8131]], grad_fn=<AddmmBackward0>)


In [6]:
input_tensor = torch.Tensor([[2, 7, 9, 5, 3]])

#Create neural network with three hidden layers
model = nn.Sequential(nn.Linear(5, 10),
                      nn.Linear(10, 15),
                      nn.Linear(15, 2))

output = model(input_tensor)
print(output)

tensor([[-1.2374,  1.3487]], grad_fn=<AddmmBackward0>)


In [7]:
model = nn.Sequential(nn.Linear(8, 4),
                      nn.Linear(4, 1))

# Calculate the number of parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"Total number of parameters: {total_params}")

Total number of parameters: 41


### `Multiplication of matrix`

* A * B is called elements wise multiplications
* A @ B is called matrix multiplications
  

In [8]:
print(temp_tensor * adjustment)

tensor([[144, 150, 156],
        [140, 146, 152]])


### `Sigmoid Activation`
The sigmoid function is essential for binary classification.

In [3]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([6.0])

# Apply sigmoid activation function
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
print(output)

tensor([0.9975])


This value indicates a high likelihood of the input belonging to the positive class

### `Softmax`
The softmax activation function is use for multi-class classification problems.

In [3]:
input_tensor = torch.tensor([2.0, 3.0, 5.0])

# Applying sofmax activation function
softmax = nn.Softmax(dim=-1)
output = softmax(input_tensor)
print(output)

tensor([0.0420, 0.1142, 0.8438])


### `Neural Networks and Activation Functions`

In [5]:
model= nn.Sequential(nn.Linear(3, 1),
                     nn.Sigmoid())

input_tensor = torch.tensor([[1.0, 0.0, 1.0]])

output = model(input_tensor)
print(output)

tensor([[0.4445]], grad_fn=<SigmoidBackward0>)


### `Running a Forward Pass`

In [10]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.layer1 = nn.Linear(6, 4)
        self.layer2 = nn.Linear(4, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        return x
    
# Example input data: 5 animals with 6 features each
input_data = torch.randn(5, 6)
model = SimpleNet()
output = model(input_data)
print(output)

tensor([[0.4633],
        [0.5607],
        [0.6028],
        [0.7641],
        [0.4234]], grad_fn=<SigmoidBackward0>)


The output is a tensor of probabilities for each animal being mammal. Probabilities above 0.5 are classified as `mammals`

In [11]:
print(input_data)

tensor([[ 0.7156,  1.0850,  0.9732, -0.6339, -0.1748,  0.6600],
        [ 0.8810, -0.8619, -0.7653, -0.4784, -0.9159, -0.2109],
        [ 0.0279,  0.8680, -0.1871, -0.8715,  0.1015, -0.8748],
        [ 0.6029, -0.8699, -0.7344,  0.9807,  1.6170,  0.0275],
        [ 0.1348,  0.5761,  0.5089,  0.1204, -0.9634, -0.3321]])


### `Multi-Class Classification with Softmax`

In [4]:
import torch.nn.functional as F

class MultiClassNet(nn.Module):
    def __init__(self):
        super(MultiClassNet, self).__init__()
        self.layer1 = nn.Linear(6, 4)
        self.layer2 = nn.Linear(4, 3)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = F.softmax(x, dim = -1)
        return x
    
input_data = torch.randn(5, 6)
model = MultiClassNet()
output = model(input_data)
print(output)


tensor([[0.4966, 0.1265, 0.3769],
        [0.5191, 0.2973, 0.1836],
        [0.5221, 0.1684, 0.3095],
        [0.5169, 0.2256, 0.2575],
        [0.5609, 0.2224, 0.2167]], grad_fn=<SoftmaxBackward0>)


Each row in the output represents probabilities for the three classes, summing to one. the class with the highest probability is the predicted label.

### `Understanding One-Hot Encoding`

In [5]:
import numpy as np

y=1
num_classes = 3

# Create the one-hot encoded vector using Numpy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes= num_classes)

print("One-hot vector using Numpy:", one_hot_numpy)
print("One-hot vector using PyTorch:", one_hot_pytorch)

One-hot vector using Numpy: [0 1 0]
One-hot vector using PyTorch: tensor([0, 1, 0])


### `Calculating Cross-Entropy Loss`

In [6]:
from torch.nn import CrossEntropyLoss

#Ground truth label
y= torch.tensor([1])

# Scores (Predictions before softmax)
scores = torch.tensor([[2.0, 1.0, 0.1]])

# Define the cross-entropy loss function
criterion = CrossEntropyLoss()

# Compute the Loss
loss = criterion(scores, y)

print("Cross-entropy loss:", loss.item())

Cross-entropy loss: 1.4170299768447876


### `Using Loss Functions to Assess Model Predictions`

In [10]:
y = torch.tensor([0])
scores = torch.tensor([[2.5, 0.3, 0.2]])
one_hot_target = F.one_hot(y, num_classes=3)

criterion = torch.nn.CrossEntropyLoss()

loss = criterion(scores.double(), y)

print("Computed Loss:", loss.item())

Computed Loss: 0.1914976636771114


### `Understanding Gradients in Neural Networks`

In [2]:
import torch
import torch.nn as nn

model = nn.Sequential(nn.Linear(16, 8),
                      nn.Linear(8, 4))

input_data = torch.randn(1, 16)
output = model(input_data)

#Define a loss function
criterion = nn.CrossEntropyLoss()
target = torch.tensor([1])
loss = criterion(output, target)

loss.backward()

# Backward pass to calculate gradients
gradient_layer_0 = model[0].weight.grad
bia_gradient_layer_0 = model[1].bias.grad

print("Gradient of the first layer's weight is:", gradient_layer_0)
print("Gradient of the first layer's bias is:", bia_gradient_layer_0)

Gradient of the first layer's weight is: tensor([[ 0.1482,  0.0043, -0.1023, -0.0039, -0.1097,  0.0224,  0.0454,  0.2888,
          0.1159,  0.0032,  0.0332,  0.1866,  0.1981,  0.0955, -0.0572, -0.0839],
        [ 0.2364,  0.0069, -0.1632, -0.0062, -0.1750,  0.0357,  0.0725,  0.4607,
          0.1848,  0.0051,  0.0530,  0.2976,  0.3160,  0.1524, -0.0912, -0.1338],
        [ 0.0718,  0.0021, -0.0496, -0.0019, -0.0531,  0.0108,  0.0220,  0.1399,
          0.0561,  0.0015,  0.0161,  0.0904,  0.0960,  0.0463, -0.0277, -0.0406],
        [-0.0584, -0.0017,  0.0403,  0.0015,  0.0432, -0.0088, -0.0179, -0.1138,
         -0.0456, -0.0013, -0.0131, -0.0735, -0.0780, -0.0376,  0.0225,  0.0330],
        [-0.2308, -0.0067,  0.1594,  0.0061,  0.1709, -0.0348, -0.0708, -0.4498,
         -0.1804, -0.0050, -0.0517, -0.2906, -0.3086, -0.1488,  0.0891,  0.1306],
        [ 0.0330,  0.0010, -0.0228, -0.0009, -0.0244,  0.0050,  0.0101,  0.0644,
          0.0258,  0.0007,  0.0074,  0.0416,  0.0441,  0.0213, 

### `Updates Weight and Bias with PyTorch`

In [3]:
import torch.optim as optim

#Define optimizer
optimizer = optim.SGD(model.parameters(), lr = 0.01)

#forward pass and calculate loss
criterion = nn.CrossEntropyLoss()
output = model(input_data)
loss = criterion(output, target)

#Backward pass to calculate gradients
loss.backward()
print("Weight before optimizer step:", model[0].weight)

#Update weights using the optimizer
optimizer.step()

#Print update weight
print("Weigts after otimizer step:", model[0].weight) 


Weight before optimizer step: Parameter containing:
tensor([[-0.0113, -0.0550, -0.2444,  0.1280,  0.0853,  0.0687,  0.1321,  0.0325,
         -0.2291,  0.2177, -0.1854,  0.1484,  0.2020,  0.1689,  0.1137,  0.0463],
        [ 0.1752,  0.2480, -0.1871,  0.0224,  0.2012, -0.2292,  0.0633,  0.0943,
          0.1150, -0.2078, -0.0101, -0.1592,  0.0765, -0.2244, -0.1416, -0.2406],
        [-0.2426, -0.0853, -0.1868, -0.1256,  0.2195, -0.0058,  0.1958, -0.1753,
          0.1177, -0.1173,  0.2420,  0.0097, -0.0499,  0.0353,  0.2160, -0.1433],
        [-0.0701, -0.0824, -0.0226,  0.1291,  0.1527, -0.1853,  0.1433,  0.2086,
         -0.1257,  0.1260, -0.1213,  0.1199, -0.0201, -0.0542, -0.1638, -0.2018],
        [ 0.0535, -0.2344, -0.1646,  0.0906, -0.2000, -0.1331, -0.1247,  0.2406,
         -0.1065, -0.1759,  0.2273,  0.1124,  0.1106,  0.1590, -0.2441, -0.0374],
        [ 0.2149,  0.0352,  0.0307,  0.0742,  0.0173,  0.1108, -0.2255,  0.1076,
          0.0543,  0.1882,  0.2127, -0.0640,  0.2478